name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        cd backend
        npm install
        npm run build
        cd ..
        cd cloud
        ls
        cd cloud
        cd src 
        ls
