name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build backend
      run:  |
        cd backend
        npm install
        npm run build
    - name: Build frontend
      run: |
        cp -a ./frontend/. public/
