name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Back4App
      env:
        BACK4APPKEY: ${{secrets.BACK4APPKEY}}
      run: | 
        curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
        b4a configure accountkey <<<"$BACK4APPKEY"
        b4a deploy

