name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Dump GitHub context
      env:
          BACK4APPKEY: ${{secrets.BACK4APPKEY}}
      run: echo "$BACK4APPKEY"
    - uses: actions/checkout@v1
    - name: Build backend
      run:  |
        cd backend
        npm install
        npm run build
    - name: Build frontend
      run: |
        cp -a ./frontend/. public/
        cd public
        ls 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Back4App
      env:
        SUPER_SECRET: ${{ secrets.Back4AppKey }}
      run: | 
        echo "$SUPER_SECRET"
        curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
        b4a configure accountkey 
